from ast import Mod
from multiprocessing import Value
from typing import Iterable, Any
from pathlib import Path

from pytest import Directory, File

class NodeType: 
    Virtual: 'NodeType'
    Mod: 'NodeType'
    Directory: 'NodeType'
    File: 'NodeType'
    Identifier: 'NodeType'
    Value: 'NodeType'
    

class DefinitionNode:
    name: str
    rel_dir:Path
    source: DefinitionNode|None
    sources: list[DefinitionNode]
    mod_sources: list[DefinitionNode]
    parent: 'DefinitionNode'|None
    type: NodeType
    line: int|None
    start_point: tuple[int, int]|None
    full_path: Path
    def __setitem__(self, key: str, value: 'DefinitionNode') -> None: ...
    def __getitem__(self, key: str) -> 'DefinitionNode': ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list['DefinitionNode']: ...
    def items(self) -> list[tuple[str, 'DefinitionNode']]: ...
    def __iter__(self) -> Iterable[str]: ...
    def __repr__(self) -> str: ...
    def setdefault(self, key: Any, default: Any = None) -> Any: ...
    def setdefault_by_dir(self, dirpath: str | Path, default: 'DefinitionNode'|None = None) -> 'DefinitionNode': ...
    def get(self, key: str, default: DefinitionNode|None = None) -> Any: ...
    def get_by_dir(self, dirpath: str|Path, default: DefinitionNode|None = None) -> 'DefinitionNode': ...
    def set_source(self, source: Any) -> None: ...
    def has_conflict(self) -> bool: ...
    def pretty_print(self, indent: int =0) -> None: ...
    
class ModNode(DefinitionNode):...
class IdentifierDefNode(DefinitionNode):
    type: NodeType # NodeType.Identifier
    line: int
    start_point: tuple[int, int]
class ValueDefNode(DefinitionNode):
    value: str
class FileDefNode(DefinitionNode):...
class DirectoryDefNode(DefinitionNode):...

    
    
        
class ParadoxModDefinitionTree:
    root: DefinitionNode
    def __init__(self) -> None: ...   
    def new_node(self, name: str, rel_dir: str|Path, value: str|None = None) -> DefinitionNode: ...
    def get_node(self, id: int) -> DefinitionNode: ...
    def get_node_num(self) -> int: ...
