from collections.abc import Iterator
from types import UnionType
from typing import Any, Self


class IndexedOrderedDict():
    def __init__(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, __key: str) -> Any: ...
    def __setitem__(self, __key: str, __value: Any) -> None: ...
    def __delitem__(self, __key: str) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self: Self, value: Any) -> UnionType | Self: ...
    def __ior__(self: Self, value: Any) -> UnionType | Self: ...
    def __reversed__(self) -> Iterator: ...
    
    def update(self, m: dict) -> None: ...
    def sort(self, *, key=None, reverse: bool=False) -> None: ...
    def keys(self) -> list: ...
    def values(self) -> list: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def clear(self) -> None: ...
    def copy(self) -> 'IndexedOrderedDict': ...
    def get(self, k: str, d: Any=None) -> Any: ...
    def pop(self, k: str, d: Any=None) -> Any: ...
    def popitem(self) -> tuple[str, Any]: ...
    def setdefault(self, k: str, d: Any=None) -> Any: ...
    def move_to_end(self, k: str, last: bool=True) -> None: ...
    def fromkeys(self, iterable) -> 'IndexedOrderedDict': ...
    
    def __getstate__(self) -> object: ...
    def __setstate__(self, state: object) -> None: ...