from tabnanny import check
from .definition_tree import DefinitionNode, ParadoxModDefinitionTree
from pathlib import Path

def extract_script_definitions(src:str, root_node:DefinitionNode|None=None)->DefinitionNode: ...
def extract_loc_definitions(src:str, root_node:DefinitionNode|None=None)->DefinitionNode: ...
def collect_mod_files(mod_dir: str|Path) -> dict[str, list[str]]: ...
def batch_collect_mod_files(mod_dirs: list[str|Path]) -> dict[str, list[str]]: ...

class ModData:
    name: str
    enabled: bool
    load_order: int
    
class DefinitionExtractor:
    workshop_dir: str|Path
    mods_dir: str|Path
    language: str
    conflict_identifiers: list[DefinitionNode]
    tree: ParadoxModDefinitionTree
    check_loc_conflicts: bool
    check_script_conflicts: bool
    def __init__(self, workshop_dir: str|Path, mods_dir: str|Path, language: str) -> None: ...
    def enroll_mods(self, mod_dirs: list[ModData]) -> None: ...
    def extract_definitions(self, max_depth: int = 0) -> DefinitionNode: ...
    def get_node_by_name(self, name: str) -> list[DefinitionNode]|None: ...
    def get_conflicts_by_mod(self) -> dict[str, list[DefinitionNode]]: ...